import Image from 'next/image'
import type { SamplePreviewHomeBlock } from '@/types/strapi'
import type { SiteLocale } from '@/lib/i18n'

export function SamplePreviewHomeBlockView({ block, locale }: { block: SamplePreviewHomeBlock; locale: SiteLocale }) {
  const isRtl = locale === 'ar'
  return (
    <section className="py-24 lg:py-32 bg-foreground text-background overflow-hidden" dir={isRtl ? 'rtl' : 'ltr'}><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl mb-16"><div className="flex items-center gap-3 mb-4"><div className="flex items-center">{isRtl ? <><span className="h-[2px] w-2 bg-signature-brass-soft rounded-full" /><span className="h-[2px] w-3 bg-signature-cobalt-soft mr-0.5 rounded-full" /></> : <><span className="h-[2px] w-3 bg-signature-cobalt-soft rounded-full" /><span className="h-[2px] w-2 bg-signature-brass-soft ml-0.5 rounded-full" /></>}</div><span className="text-[10px] uppercase tracking-[0.2em] text-background/50">{block.eyebrow}</span></div><h2 className="font-serif text-3xl lg:text-4xl xl:text-5xl font-light leading-tight text-background text-balance">{block.title}</h2><p className="mt-6 text-base text-background/60 max-w-2xl">{block.description}</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">{block.items?.map((artifact,index)=><div key={artifact.id ?? `${artifact.title}-${index}`} className="group relative bg-background/[0.03] border border-background/10 rounded-sm overflow-hidden hover:bg-background/[0.06] hover:border-background/20 transition-all duration-300">{index===0 && <div className={`absolute top-0 ${isRtl ? 'right-0' : 'left-0'} z-10`}><div className={`absolute top-0 ${isRtl ? 'right-0 rounded-l-full' : 'left-0 rounded-r-full'} w-4 h-[2px] bg-signature-cobalt-soft/60`} /><div className={`absolute top-0 ${isRtl ? 'right-0' : 'left-0'} h-4 w-[2px] bg-signature-cobalt-soft/60 rounded-b-full`} /><div className={`absolute top-[2px] ${isRtl ? 'right-4' : 'left-4'} w-2 h-[1.5px] bg-signature-brass-soft/50 rounded-full`} /></div>}<div className="relative aspect-[4/3] overflow-hidden">{artifact.imageUrl ? <Image src={artifact.imageUrl} alt={artifact.imageAlt || artifact.title} fill className="object-cover object-center group-hover:scale-[1.02] transition-transform duration-500" sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 25vw" /> : null}<div className="absolute inset-0 bg-gradient-to-t from-foreground/40 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" /></div><div className="p-5"><h3 className="font-serif text-lg text-background mb-1.5 group-hover:text-background transition-colors">{artifact.title}</h3><p className="text-sm text-background/50 leading-relaxed">{artifact.subtitle}</p></div></div>)}</div>{block.note ? <div className="mt-12 pt-8 border-t border-background/10"><p className="text-sm text-background/40 text-center">{block.note}</p></div> : null}</div></section>
  )
}
