type SeedLocale = 'ru' | 'en' | 'ar'

type SeedPage = {
  title: string
  slug: string
  template: 'for-startups' | 'for-agencies' | 'pricing' | 'method'
  seo: {
    metaTitle: string
    metaDescription: string
  }
  blocks: any[]
}

type LocalePages = Record<SeedLocale, SeedPage[]>

const VIDEO_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

export const PHASE_E_PAGES: LocalePages = {
  ru: [
    {
      title: 'Для стартапов',
      slug: 'for-startups',
      template: 'for-startups',
      seo: {
        metaTitle: 'Для стартапов — Atelier Meridian',
        metaDescription: 'Для стартапов, которым нужен ясный продукт до начала разработки.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'Для стартапов',
          title: 'Для стартапов, которым нужен ясный продукт до начала разработки',
          description:
            'Помогаем startup-командам собрать структуру сайта, web-продукта или mobile app, чтобы проект было проще показать инвесторам, объяснить команде и передать в разработку.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
          tags: [
            { label: 'MVP' },
            { label: 'Investor-ready prototype' },
            { label: 'SaaS interfaces' },
            { label: 'Redesign' },
          ],
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Зачем приходят',
          title: 'Зачем стартапы приходят в Atelier Meridian',
          description:
            'На раннем этапе проекту редко нужен просто дизайн. Чаще всего не хватает ясности: что показать, какие сценарии важны и как собрать MVP.',
          variant: 'audience',
          columns: '4',
          items: [
            { title: 'Когда идея ещё не собрана в продукт', description: 'Превращаем rough concept в понятную структуру экранов, сценариев и приоритетов.' },
            { title: 'Когда нужно показать продукт инвестору', description: 'Собираем investor-ready prototype и визуальную подачу.' },
            { title: 'Когда нужно запустить MVP быстрее', description: 'Убираем лишнее и фокусируемся на ключевых сценариях и интерфейсах.' },
            { title: 'Когда разработке нужен ясный следующий шаг', description: 'Готовим материалы и интерфейсную логику для handoff.' },
          ],
        },
        {
          __component: 'page.video-section',
          eyebrow: 'Walkthrough',
          title: 'Как выглядит работа над startup-проектом',
          description: 'От product framing и экранной карты до prototype и материалов для передачи в разработку.',
          videoUrl: VIDEO_URL,
          note: 'Замените ссылку на финальный walkthrough в Strapi.',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Решения',
          title: 'С чем мы помогаем startup-командам',
          variant: 'deliverables',
          columns: '3',
          items: [
            { title: 'Сайты и landing pages', description: 'Структура и дизайн сайта для startup-проекта — от концепции до build-ready результата.' },
            { title: 'Product websites', description: 'Сайты, которые объясняют ценность продукта, показывают функции и конвертируют посетителей.' },
            { title: 'Web products и SaaS-интерфейсы', description: 'User flows, экранная карта, prototype и дизайн интерфейсов до build-этапа.' },
            { title: 'Mobile apps', description: 'Структура приложения, ключевые user flows и визуальное направление.' },
            { title: 'Redesign продукта', description: 'Улучшаем UX/UI существующего сайта или приложения.' },
          ],
        },
        {
          __component: 'page.steps',
          eyebrow: 'Процесс',
          title: 'Как это обычно происходит',
          variant: 'process',
          items: [
            { number: '01', title: 'Brief', description: 'Собираем задачу, цели, ограничения и контекст проекта.' },
            { number: '02', title: 'Структура', description: 'Определяем, какие сценарии и экраны действительно нужны на старте.' },
            { number: '03', title: 'Приоритеты', description: 'Отделяем MVP от второстепенного. Фокусируем на главном.' },
            { number: '04', title: 'Интерфейсы', description: 'Собираем prototype, сайт или mobile screens в понятную систему.' },
            { number: '05', title: 'Следующий этап', description: 'Готовим рекомендации и материалы для передачи в разработку или следующего pitch.' },
          ],
        },
        {
          __component: 'page.faq',
          title: 'Частые вопросы',
          items: [
            { question: 'Можно ли прийти только с идеей?', answer: 'Да. Мы часто работаем с проектами на стадии идеи или rough concept.' },
            { question: 'Подходит ли это для MVP?', answer: 'Да, это один из самых частых запросов: сфокусировать MVP и убрать лишнее.' },
            { question: 'Можно ли сделать сначала сайт, а потом продукт?', answer: 'Да. Многие стартапы начинают с сайта для валидации или fundraising.' },
            { question: 'Вы помогаете только с визуалом?', answer: 'Нет. Мы работаем и со структурой продукта: сценарии, логика экранов и приоритеты.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Не уверены, с чего начать: с сайта, MVP или prototype?',
          description: 'Опишите задачу — мы предложим подходящий формат работы, ориентир по срокам и следующий шаг.',
          buttonLabel: 'Получить предложение',
          buttonHref: '/ru/get-proposal',
          secondaryButtonLabel: 'Посмотреть цены',
          secondaryButtonHref: '/ru/pricing',
        },
      ],
    },
    {
      title: 'Для партнёров',
      slug: 'for-agencies',
      template: 'for-agencies',
      seo: {
        metaTitle: 'Для партнёров — Atelier Meridian',
        metaDescription: 'Внешний premium-партнёр по интерфейсам и продуктовой структуре.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'Для партнёров',
          title: 'Для партнёров, которым нужен внешний premium-партнёр по интерфейсам и продуктовой структуре',
          description: 'Подключаемся как внешний premium-партнёр для агентств, integrators и delivery-команд.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
          tags: [{ label: 'White-label' }, { label: 'Presale support' }, { label: 'Dashboards' }, { label: 'Portals' }],
        },
        {
          __component: 'page.rich-text',
          title: 'Не просто подрядчик по дизайну, а внешний product / interface partner',
          body: 'Atelier Meridian подключается туда, где партнёрской команде не хватает времени, внутренней UX/UI-ёмкости или сильной продуктовой упаковки.',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Кому подходит',
          title: 'Кому подходит этот формат',
          variant: 'audience',
          columns: '3',
          items: [
            { title: 'Web-студии и digital-агентства', description: 'Внешний сильный UX/UI / product-слой для client-facing work.' },
            { title: 'System integrators', description: 'Сложные проекты, где важно собрать логику до разработки.' },
            { title: 'Outsourcing и dev shops', description: 'Внешняя premium-команда для product clarity и interfaces.' },
            { title: 'Delivery-команды', description: 'Усиление client-facing delivery, presale и прототипирования.' },
          ],
        },
        {
          __component: 'page.video-section',
          eyebrow: 'Walkthrough',
          title: 'Как выглядит подключение внешнего product / interface layer',
          description: 'От brief и scope до prototype и материалов для client delivery или handoff в разработку.',
          videoUrl: VIDEO_URL,
          note: 'Замените ссылку на финальный walkthrough в Strapi.',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Типы проектов',
          title: 'С какими проектами подключаемся',
          variant: 'projects',
          columns: '3',
          items: [
            { title: 'Сайты и корпоративные сайты', description: 'От лендингов до сложных корпоративных сайтов с multiple user journeys.' },
            { title: 'Редизайн сайта и UX/UI-улучшение', description: 'Переработка существующего сайта — от логики до визуала.' },
            { title: 'Digital-системы и B2B-платформы', description: 'Сложные интерфейсы с ролями, сценариями и модулями.' },
            { title: 'Клиентские порталы и dashboards', description: 'Service portals, кабинеты, operational dashboards.' },
            { title: 'Mobile apps', description: 'iOS/Android приложения с фокусом на UX и platform fit.' },
            { title: 'Прототипы для presale', description: 'Быстрая упаковка концепции в убедительный prototype.' },
          ],
        },
        {
          __component: 'page.steps',
          eyebrow: 'Процесс',
          title: 'Как обычно устроена работа с партнёрами',
          variant: 'process',
          items: [
            { number: '01', title: 'Контекст проекта', description: 'Вы делитесь brief, client notes или rough описанием.' },
            { number: '02', title: 'Scope и ограничения', description: 'Согласовываем scope, сроки и формат взаимодействия.' },
            { number: '03', title: 'Структура решения', description: 'Собираем продуктовую логику: роли, сценарии, экранную карту.' },
            { number: '04', title: 'Интерфейсы и prototype', description: 'Проектируем ключевые экраны и prototype.' },
            { number: '05', title: 'Передача в разработку или клиенту', description: 'Формируем материалы для dev-команды или client presentation.' },
          ],
        },
        {
          __component: 'page.faq',
          title: 'Частые вопросы',
          items: [
            { question: 'Подходит ли это только для агентств?', answer: 'Нет. Формат подходит и integrators, outsourcing-командам, dev shops и delivery-командам.' },
            { question: 'Можно ли подключаться white-label?', answer: 'Да. White-label — один из наших стандартных форматов.' },
            { question: 'Можно ли прийти только с client brief?', answer: 'Конечно. Мы работаем с любым уровнем готовности.' },
            { question: 'Как быстро можно стартовать?', answer: 'Обычно через 3–5 рабочих дней после согласования scope.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Нужен внешний product / UX / interface layer под проект?',
          description: 'Опишите задачу — мы предложим подходящий формат подключения, ориентир по срокам и следующий шаг.',
          buttonLabel: 'Получить предложение',
          buttonHref: '/ru/get-proposal',
          secondaryButtonLabel: 'Посмотреть цены',
          secondaryButtonHref: '/ru/pricing',
        },
      ],
    },
    {
      title: 'Цены',
      slug: 'pricing',
      template: 'pricing',
      seo: {
        metaTitle: 'Цены — Atelier Meridian',
        metaDescription: 'Пакеты и форматы работы Atelier Meridian.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'Форматы работы и цены',
          title: 'Цены и форматы работы',
          description: 'Atelier Meridian работает через ограниченное число структурированных форматов — от product framing до build-ready prototype и white-label поддержки.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'На главную',
          secondaryCtaHref: '/ru',
          tags: [{ label: 'Structured delivery' }, { label: 'Build-ready output' }, { label: 'Direct collaboration' }],
        },
        {
          __component: 'page.rich-text',
          title: 'Структурированные форматы вместо размытого почасового биллинга',
          body: 'Мы работаем не через open-ended часы, а через понятные пакеты: framing, prototype и partner support. Это помогает быстрее согласовать scope и ожидания.',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Форматы',
          title: 'Основные пакеты',
          variant: 'packages',
          columns: '3',
          items: [
            { title: 'Product Framing Sprint', description: 'Структурирование продукта до начала дизайна и разработки.' },
            { title: 'Build-Ready Prototype', description: 'Прототип и ключевые интерфейсы для презентации или передачи в разработку.' },
            { title: 'White-Label Partner Desk', description: 'Партнёрский формат для агентств, integrators и delivery-команд.' },
          ],
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Рекомендации',
          title: 'Как понять, какой формат подходит вам',
          variant: 'decision-support',
          columns: '3',
          items: [
            { title: 'Если у вас ещё нет чёткой структуры продукта', description: 'Start with Product Framing Sprint.' },
            { title: 'Если нужно показать продукт или передать в разработку', description: 'Build-Ready Prototype covers screens, prototype, and handoff materials.' },
            { title: 'Если вы агентство или integrator', description: 'White-Label Partner Desk gives you an external premium layer.' },
          ],
        },
        {
          __component: 'page.faq',
          title: 'Частые вопросы о форматах и стоимости',
          items: [
            { question: 'Можно ли прийти с нестандартным объёмом работ?', answer: 'Да. Packages — это ориентиры, а не жёсткие рамки.' },
            { question: 'Подходит ли pricing только для сайтов?', answer: 'Нет. Подход подходит и для digital-систем, порталов, dashboards и mobile apps.' },
            { question: 'Подписываете ли вы NDA?', answer: 'Да. NDA — стандартная практика.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Закажите дизайн сайта, системы или приложения',
          description: 'Опишите проект — сайт, портал, B2B-платформу или mobile app. Мы предложим формат, сроки и стоимость.',
          buttonLabel: 'Получить предложение',
          buttonHref: '/ru/get-proposal',
          secondaryButtonLabel: 'На главную',
          secondaryButtonHref: '/ru',
        },
      ],
    },
    {
      title: 'Как мы работаем',
      slug: 'method',
      template: 'method',
      seo: {
        metaTitle: 'Метод работы — Atelier Meridian',
        metaDescription: 'Как мы превращаем задачу в структуру, интерфейс и ясный следующий шаг.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'Как мы работаем',
          title: 'Как мы превращаем задачу в структуру, интерфейс и понятный следующий шаг',
          description: 'Работаем с сайтами, digital-системами, порталами, dashboards и мобильными приложениями. Сначала структурируем продукт — затем проектируем интерфейс.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
        },
        {
          __component: 'page.rich-text',
          title: 'Не просто дизайн, а структурированный рабочий процесс',
          body: 'Мы начинаем не с отдельных экранов, а с целей, ограничений, ролей, user flows и логики экранов. Так появляется более сильная база для интерфейсного дизайна и handoff в разработку.',
        },
        {
          __component: 'page.video-section',
          eyebrow: 'Walkthrough',
          title: 'Как выглядит путь от задачи к prototype и handoff',
          description: 'Brief, структура, flows, screens, prototype и development handoff.',
          videoUrl: VIDEO_URL,
          note: 'Замените ссылку на финальный walkthrough в Strapi.',
        },
        {
          __component: 'page.steps',
          eyebrow: 'Этапы',
          title: 'Как устроен процесс — от первого контакта до передачи в разработку',
          variant: 'process',
          items: [
            { number: '01', title: 'Асинхронный brief', description: 'Понимаем задачу без долгих встреч.' },
            { number: '02', title: 'Структурирование продукта', description: 'Фиксируем архитектуру и границы.' },
            { number: '03', title: 'Проектирование интерфейса', description: 'Создаём user flows и wireframes.' },
            { number: '04', title: 'Prototype и дизайн', description: 'Собираем premium-интерфейс.' },
            { number: '05', title: 'Передача в разработку', description: 'Готовим материалы для dev-команды.' },
          ],
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Результаты',
          title: 'Что вы получаете в результате работы',
          variant: 'deliverables',
          columns: '3',
          items: [
            { title: 'Структура проекта', description: 'Цели, роли, сценарии и приоритеты — зафиксированная архитектура продукта.' },
            { title: 'Пользовательские сценарии', description: 'User flows и логика взаимодействия.' },
            { title: 'Экранная карта', description: 'Визуальная структура экранов и переходов.' },
            { title: 'Интерактивный prototype', description: 'Кликабельная демонстрация продукта.' },
            { title: 'Детальный дизайн', description: 'Premium-интерфейсы для ключевых экранов.' },
            { title: 'Материалы для разработки', description: 'Спецификации, assets и documentation.' },
          ],
        },
        {
          __component: 'page.faq',
          title: 'Частые вопросы о процессе',
          items: [
            { question: 'Вы всегда начинаете с brief?', answer: 'Мы стартуем с любого контекста: structured brief, rough notes, existing product или product idea.' },
            { question: 'Можно прийти с неполными материалами?', answer: 'Да. Многие проекты стартуют с incomplete inputs — мы помогаем их структурировать.' },
            { question: 'Подходит ли это для redesign?', answer: 'Да. Redesign часто выигрывает от структурированного анализа и product framing.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Готовы начать работу над проектом?',
          description: 'Расскажите о вашей задаче — сайт, digital-система, портал или mobile app. Мы предложим формат, сроки и стоимость.',
          buttonLabel: 'Получить предложение',
          buttonHref: '/ru/get-proposal',
          secondaryButtonLabel: 'Посмотреть цены',
          secondaryButtonHref: '/ru/pricing',
        },
      ],
    },
  ],
  en: [
    {
      title: 'For Startups',
      slug: 'for-startups',
      template: 'for-startups',
      seo: {
        metaTitle: 'For Startups — Atelier Meridian',
        metaDescription: 'For startups that need product clarity before development.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'For Startups',
          title: 'For startups that need product clarity before development',
          description: 'Atelier Meridian helps founders and startup teams turn rough product ideas and early workflows into clear structure, premium interfaces, and clickable prototypes.',
          primaryCtaLabel: 'Get Proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'View Pricing',
          secondaryCtaHref: '/en/pricing',
          tags: [{ label: 'MVP' }, { label: 'Investor-ready prototype' }, { label: 'SaaS interfaces' }],
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Why teams come to us',
          title: 'Why startup teams come to Atelier Meridian',
          variant: 'audience',
          columns: '4',
          items: [
            { title: 'When the idea is not yet a product', description: 'We turn a rough concept into screen structure, scenarios, and priorities.' },
            { title: 'When the product must be shown to investors', description: 'We prepare investor-ready prototypes and stronger presentation.' },
            { title: 'When the MVP must move faster', description: 'We reduce noise and focus on the core scenarios.' },
            { title: 'When development needs a clearer next step', description: 'We prepare materials and logic for easier handoff.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Not sure whether to start with a site, MVP, or prototype?',
          description: 'Describe the task and we will suggest the right format, timeline, and next step.',
          buttonLabel: 'Get Proposal',
          buttonHref: '/en/get-proposal',
          secondaryButtonLabel: 'View Pricing',
          secondaryButtonHref: '/en/pricing',
        },
      ],
    },
    {
      title: 'For Partners',
      slug: 'for-agencies',
      template: 'for-agencies',
      seo: {
        metaTitle: 'For Partners — Atelier Meridian',
        metaDescription: 'External premium product and interface layer for agencies, integrators, and delivery teams.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'For Partners',
          title: 'For partners who need an external premium product and interface layer',
          description: 'Atelier Meridian works as an external premium partner when projects need stronger product structure, better interface quality, or a more credible prototype.',
          primaryCtaLabel: 'Get Proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'View Pricing',
          secondaryCtaHref: '/en/pricing',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Who this is for',
          title: 'Who this format is for',
          variant: 'audience',
          columns: '3',
          items: [
            { title: 'Digital agencies', description: 'An external UX/UI and product layer for client-facing work.' },
            { title: 'System integrators', description: 'Complex projects where logic and presentation must be clarified before build.' },
            { title: 'Delivery teams', description: 'Support for client-facing delivery, presale, and prototyping.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Need an external product / UX / interface layer for a project?',
          description: 'Describe the task and we will suggest the right collaboration format, timeline, and next step.',
          buttonLabel: 'Get Proposal',
          buttonHref: '/en/get-proposal',
          secondaryButtonLabel: 'View Pricing',
          secondaryButtonHref: '/en/pricing',
        },
      ],
    },
    {
      title: 'Pricing',
      slug: 'pricing',
      template: 'pricing',
      seo: {
        metaTitle: 'Pricing — Atelier Meridian',
        metaDescription: 'Structured engagement formats and pricing.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'Formats & Pricing',
          title: 'Pricing and engagement formats',
          description: 'Atelier Meridian works in a small number of structured formats — from product framing and investor-ready preparation to build-ready prototypes and white-label support.',
          primaryCtaLabel: 'Get Proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'Back to Home',
          secondaryCtaHref: '/en',
        },
        {
          __component: 'page.cards-grid',
          eyebrow: 'Formats',
          title: 'Core packages',
          variant: 'packages',
          columns: '3',
          items: [
            { title: 'Product Framing Sprint', description: 'Product structure before design and development.' },
            { title: 'Build-Ready Prototype', description: 'Prototype and key interfaces for presentation or handoff.' },
            { title: 'White-Label Partner Desk', description: 'Partner format for agencies, integrators, and delivery teams.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Order a website, system, or app design package',
          description: 'Describe the project and we will suggest the right format, timeline, and price range.',
          buttonLabel: 'Get Proposal',
          buttonHref: '/en/get-proposal',
          secondaryButtonLabel: 'Back to Home',
          secondaryButtonHref: '/en',
        },
      ],
    },
    {
      title: 'How We Work',
      slug: 'method',
      template: 'method',
      seo: {
        metaTitle: 'How We Work — Atelier Meridian',
        metaDescription: 'How we turn a task into structure, interface, and a clear next step.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'How We Work',
          title: 'How we turn a task into structure, interface, and a clear next step',
          description: 'Atelier Meridian works through a focused sequence: understanding the task, clarifying structure, shaping user flows, designing key interfaces, and preparing materials for the next stage.',
          primaryCtaLabel: 'Get Proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'View Pricing',
          secondaryCtaHref: '/en/pricing',
        },
        {
          __component: 'page.steps',
          eyebrow: 'Process',
          title: 'From first contact to development handoff',
          variant: 'process',
          items: [
            { number: '01', title: 'Async brief', description: 'We understand the task without unnecessary calls.' },
            { number: '02', title: 'Product structure', description: 'Goals, roles, scenarios, and priorities become clear.' },
            { number: '03', title: 'Interface design', description: 'User flows, wireframes, and screen logic take shape.' },
            { number: '04', title: 'Prototype and design', description: 'Premium prototype and key screens for presentation and validation.' },
            { number: '05', title: 'Development handoff', description: 'Specifications, assets, and support for the next step.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'Ready to start work on the project?',
          description: 'Tell us about the task and we will suggest the right format, timeline, and next step.',
          buttonLabel: 'Get Proposal',
          buttonHref: '/en/get-proposal',
          secondaryButtonLabel: 'View Pricing',
          secondaryButtonHref: '/en/pricing',
        },
      ],
    },
  ],
  ar: [
    {
      title: 'للشركات الناشئة',
      slug: 'for-startups',
      template: 'for-startups',
      seo: {
        metaTitle: 'للشركات الناشئة — Atelier Meridian',
        metaDescription: 'للشركات الناشئة التي تحتاج إلى وضوح المنتج قبل بدء التطوير.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'للشركات الناشئة',
          title: 'للشركات الناشئة التي تحتاج إلى وضوح المنتج قبل بدء التطوير',
          description: 'يساعد Atelier Meridian المؤسسين وفرق الشركات الناشئة على تحويل الفكرة الأولية ومتطلبات المنتج غير المكتملة إلى هيكل واضح وواجهات متميزة ونموذج أولي قابل للعرض.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'اطلع على الأسعار',
          secondaryCtaHref: '/ar/pricing',
        },
        {
          __component: 'page.cta',
          title: 'غير متأكد هل تبدأ بالموقع أم الـ MVP أم النموذج الأولي؟',
          description: 'صف المهمة وسنقترح الصيغة المناسبة والجدول الزمني والخطوة التالية.',
          buttonLabel: 'اطلب عرضاً',
          buttonHref: '/ar/get-proposal',
          secondaryButtonLabel: 'اطلع على الأسعار',
          secondaryButtonHref: '/ar/pricing',
        },
      ],
    },
    {
      title: 'للشركاء',
      slug: 'for-agencies',
      template: 'for-agencies',
      seo: {
        metaTitle: 'للشركاء — Atelier Meridian',
        metaDescription: 'طبقة خارجية متميزة في هيكلة المنتج وتصميم الواجهات للوكالات والفرق التقنية.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'للشركاء',
          title: 'للشركاء الذين يحتاجون إلى طبقة خارجية متميزة في هيكلة المنتج وتصميم الواجهات',
          description: 'يعمل Atelier Meridian كشريك خارجي متميز عندما تحتاج الفرق إلى هيكل أوضح للمنتج أو جودة أعلى في الواجهات أو نموذج أولي أكثر إقناعاً.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'اطلع على الأسعار',
          secondaryCtaHref: '/ar/pricing',
        },
        {
          __component: 'page.cta',
          title: 'هل تحتاج إلى طبقة خارجية في المنتج وUX والواجهات؟',
          description: 'صف المهمة وسنقترح صيغة التعاون والمدة والخطوة التالية.',
          buttonLabel: 'اطلب عرضاً',
          buttonHref: '/ar/get-proposal',
          secondaryButtonLabel: 'اطلع على الأسعار',
          secondaryButtonHref: '/ar/pricing',
        },
      ],
    },
    {
      title: 'الأسعار',
      slug: 'pricing',
      template: 'pricing',
      seo: {
        metaTitle: 'الأسعار — Atelier Meridian',
        metaDescription: 'صيغ العمل والأسعار في Atelier Meridian.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'صيغ العمل والأسعار',
          title: 'الأسعار وصيغ العمل',
          description: 'يعمل Atelier Meridian من خلال عدد محدود من الصيغ الواضحة والمنظمة — من هيكلة المنتج المبكرة إلى النماذج الأولية الجاهزة للتطوير ودعم الشركاء.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'العودة إلى الرئيسية',
          secondaryCtaHref: '/ar',
        },
        {
          __component: 'page.cta',
          title: 'اطلب تصميم موقع أو نظام أو تطبيق',
          description: 'صف المشروع وسنقترح الصيغة المناسبة والمدة والنطاق السعري.',
          buttonLabel: 'اطلب عرضاً',
          buttonHref: '/ar/get-proposal',
          secondaryButtonLabel: 'العودة إلى الرئيسية',
          secondaryButtonHref: '/ar',
        },
      ],
    },
    {
      title: 'كيف نعمل',
      slug: 'method',
      template: 'method',
      seo: {
        metaTitle: 'كيف نعمل — Atelier Meridian',
        metaDescription: 'كيف نحوّل المهمة إلى هيكل واضح وواجهة متميزة وخطوة تالية عملية.',
      },
      blocks: [
        {
          __component: 'page.hero',
          eyebrow: 'كيف نعمل',
          title: 'كيف نحوّل المهمة إلى هيكل واضح وواجهة متميزة وخطوة تالية عملية',
          description: 'يعمل Atelier Meridian من خلال تسلسل مركز وواضح: فهم المهمة، وتوضيح هيكل المنتج، وبناء مسارات الاستخدام، وتنظيم منطق الشاشات، ثم إعداد نموذج أولي ومخرجات تسهّل المرحلة التالية.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'اطلع على الأسعار',
          secondaryCtaHref: '/ar/pricing',
        },
        {
          __component: 'page.steps',
          eyebrow: 'العملية',
          title: 'من أول تواصل حتى تسليم المواد للتطوير',
          variant: 'process',
          items: [
            { number: '01', title: 'Brief غير متزامن', description: 'نفهم المهمة دون اجتماعات طويلة.' },
            { number: '02', title: 'هيكلة المنتج', description: 'نوضح الأهداف والأدوار والسيناريوهات والأولويات.' },
            { number: '03', title: 'تصميم الواجهة', description: 'نبني مسارات الاستخدام ومنطق الشاشات.' },
            { number: '04', title: 'النموذج الأولي والتصميم', description: 'نعد نموذجاً أولياً وواجهات أساسية للعرض والمراجعة.' },
            { number: '05', title: 'التسليم للتطوير', description: 'نجهّز المواصفات والمواد والدعم للمرحلة التالية.' },
          ],
        },
        {
          __component: 'page.cta',
          title: 'هل أنتم جاهزون لبدء العمل على المشروع؟',
          description: 'أخبرونا عن المهمة وسنقترح الصيغة المناسبة والمدة والخطوة التالية.',
          buttonLabel: 'اطلب عرضاً',
          buttonHref: '/ar/get-proposal',
          secondaryButtonLabel: 'اطلع على الأسعار',
          secondaryButtonHref: '/ar/pricing',
        },
      ],
    },
  ],
}
