type SeedLocale = 'ru' | 'en' | 'ar'

type SeedPage = {
  title: string
  slug: string
  template: 'concepts' | 'get-proposal'
  seo: {
    metaTitle: string
    metaDescription: string
  }
  blocks: any[]
}

type LocalePages = Record<SeedLocale, SeedPage[]>

const VIDEO_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

const RU_CONCEPT_ITEMS = [
  { id: 'b2b-platform', label: 'B2B-платформа и внутренняя система' },
  { id: 'mobile-app', label: 'Дизайн мобильного приложения' },
  { id: 'client-portal', label: 'Клиентский портал и dashboard' },
  { id: 'b2b-website', label: 'Корпоративный сайт для B2B-компании' },
  { id: 'startup-landing', label: 'Investor-ready landing page' },
  { id: 'saas-interface', label: 'SaaS-интерфейс для web-продукта' },
  { id: 'booking-platform', label: 'Service platform / booking interface' },
]

const EN_CONCEPT_ITEMS = [
  { id: 'b2b-platform', label: 'B2B Platform & Internal System' },
  { id: 'mobile-app', label: 'Mobile App Design' },
  { id: 'client-portal', label: 'Client Portal & Dashboard' },
  { id: 'b2b-website', label: 'Corporate Website for a B2B Company' },
  { id: 'startup-landing', label: 'Investor-Ready Landing Page' },
  { id: 'saas-interface', label: 'SaaS Interface for a Web Product' },
  { id: 'booking-platform', label: 'Service Platform / Booking Interface' },
]

const AR_CONCEPT_ITEMS = [
  { id: 'b2b-platform', label: 'منصة B2B ونظام داخلي' },
  { id: 'mobile-app', label: 'تصميم تطبيق جوال' },
  { id: 'client-portal', label: 'بوابة عميل ولوحة تحكم' },
  { id: 'b2b-website', label: 'موقع شركة B2B' },
  { id: 'startup-landing', label: 'صفحة هبوط جاهزة للمستثمر' },
  { id: 'saas-interface', label: 'واجهة SaaS لمنتج ويب' },
  { id: 'booking-platform', label: 'منصة خدمة / واجهة حجز' },
]

export const PHASE_F_PAGES: LocalePages = {
  ru: [
    {
      title: 'Концепты',
      slug: 'concepts',
      template: 'concepts',
      seo: {
        metaTitle: 'Концепты студии | Atelier Meridian',
        metaDescription:
          'Демонстрационные проекты Atelier Meridian — сайты, digital-системы, web-продукты, клиентские порталы и мобильные приложения.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'concepts-hero',
          eyebrow: 'Studio Concepts',
          title: 'Концепты студии: как может выглядеть ваш продукт до разработки',
          description:
            'Подборка демонстрационных направлений Atelier Meridian — сайты, digital-системы, клиентские порталы, SaaS-интерфейсы и мобильные приложения.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
          tags: [
            { label: 'B2B systems' },
            { label: 'Mobile apps' },
            { label: 'Client portals' },
            { label: 'Corporate websites' },
          ],
        },
        {
          __component: 'page.rich-text',
          sectionId: 'concepts-intro',
          title: 'Не шаблоны, а ориентиры для продукта и презентации',
          body:
            'Эти концепты показывают, как Atelier Meridian структурирует сложный digital-продукт до начала разработки: от narrative и screen architecture до prototype и handoff-материалов.',
        },
        {
          __component: 'page.concept-nav',
          sectionId: 'concepts-nav',
          title: 'Типовые направления',
          items: RU_CONCEPT_ITEMS.map((item) => ({ anchorId: item.id, label: item.label })),
        },
        {
          __component: 'page.concept-section',
          sectionId: 'b2b-platform',
          categoryLabel: 'ДИЗАЙН B2B-СИСТЕМ',
          title: 'B2B-платформа и внутренняя система',
          intro:
            'Концепт для сложной операционной среды, где нужно собрать workflow, роли, согласования и логику команды в одну понятную digital-систему.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Собрать сложный workflow с несколькими ролями, approval paths и dashboard-логикой в одну coherent system.' },
            { label: 'Structured', value: 'Роли и права, ключевые user flows, screen map, module logic и повседневные сценарии работы команды.' },
            { label: 'Delivered', value: 'Premium prototype, интерфейсная система, структура ключевых экранов и материалы для передачи в разработку.' },
            { label: 'Suitable for', value: 'B2B-платформы, внутренние системы, operational tools и complex admin interfaces.' },
          ],
          ctaLabel: 'Обсудить похожий проект',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'mobile-app',
          categoryLabel: 'ДИЗАЙН МОБИЛЬНЫХ ПРИЛОЖЕНИЙ',
          title: 'Дизайн мобильного приложения',
          intro:
            'Mobile-first концепт, который можно показать инвестору, использовать в pitch или взять как credible base для следующего этапа разработки.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Упаковать fintech или service-продукт в понятный mobile-first формат для инвестора и delivery-команды.' },
            { label: 'Structured', value: 'User flows, onboarding flow, логику основных экранов, priority modules и общую структуру приложения.' },
            { label: 'Delivered', value: 'Investor-ready prototype, visual direction, ключевые экраны и materials for next-stage delivery.' },
            { label: 'Suitable for', value: 'Mobile apps, MVP, investor-ready concept и redesign мобильных продуктов.' },
          ],
          ctaLabel: 'Получить предложение',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'client-portal',
          categoryLabel: 'PORTAL & DASHBOARD DESIGN',
          title: 'Клиентский портал и dashboard',
          intro:
            'Концепт сервиса, где сложный процесс превращён в client portal с прозрачной навигацией, статусами, workflow-логикой и role-based структурой.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Превратить сложный service process в понятный портал с workflow и role-based access.' },
            { label: 'Structured', value: 'Portal architecture, user scenarios, service statuses, screen matrix и ключевые interaction points.' },
            { label: 'Delivered', value: 'Структура интерфейсов, prototype ключевых экранов, UI-direction и package for development.' },
            { label: 'Suitable for', value: 'Service portals, account areas, dashboards и внутренних сервисных интерфейсов.' },
          ],
          ctaLabel: 'Обсудить портал',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'b2b-website',
          categoryLabel: 'ДИЗАЙН САЙТОВ',
          title: 'Корпоративный сайт для B2B-компании',
          intro:
            'Концепт корпоративного сайта для premium B2B-компании, который помогает ясно объяснить сложный сервис и усилить доверие.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Создать premium corporate website, который объясняет сложный B2B-сервис и усиливает trust at first contact.' },
            { label: 'Structured', value: 'Архитектуру сайта, hierarchy of content blocks, логику ключевых страниц и сценарии навигации.' },
            { label: 'Delivered', value: 'Визуальная концепция сайта, структура основных страниц и UI-система для web interface.' },
            { label: 'Suitable for', value: 'B2B-компаний, integrators, outsourcing-команд и premium corporate websites.' },
          ],
          ctaLabel: 'Хочу похожий сайт',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'startup-landing',
          categoryLabel: 'STARTUP WEBSITE DESIGN',
          title: 'Investor-ready landing page для startup-продукта',
          intro:
            'Landing page concept для раннего продукта, собранный так, чтобы идею было проще объяснить инвестору, партнёру и первым пользователям.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Упаковать ранний продукт в landing page, который быстро объясняет идею, value и core user logic.' },
            { label: 'Structured', value: 'Первый экран, product narrative, порядок смысловых блоков и ключевые proof points.' },
            { label: 'Delivered', value: 'Landing concept, site structure, visual direction и набор launch/pitch screens.' },
            { label: 'Suitable for', value: 'Startup websites, launch pages, investor presentation и early-stage positioning.' },
          ],
          ctaLabel: 'Получить предложение',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'saas-interface',
          categoryLabel: 'WEB PRODUCT DESIGN',
          title: 'SaaS-интерфейс для web-продукта',
          intro:
            'Концепт интерфейса для web-продукта, где сложная функциональность превращается в понятную, масштабируемую систему.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Собрать интерфейс так, чтобы сложная функциональность выглядела ясно, modern и ready to scale.' },
            { label: 'Structured', value: 'Key user flows, screen architecture, product modules, priority workflows и hierarchy of sections.' },
            { label: 'Delivered', value: 'Prototype, структура ключевых экранов, базовая component system и handoff materials.' },
            { label: 'Suitable for', value: 'SaaS, dashboards, web products, startup software и B2B digital tools.' },
          ],
          ctaLabel: 'Обсудить SaaS',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'booking-platform',
          categoryLabel: 'SERVICE PLATFORM DESIGN',
          title: 'Сервисная платформа / booking interface',
          intro:
            'Концепт customer-facing платформы, где сложный сервис превращается в понятный поиск, booking flow и прозрачный клиентский путь.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Превратить сложный клиентский сервис в digital product с прозрачным search, selection и booking flow.' },
            { label: 'Structured', value: 'Customer journey, service logic, key decision points, statuses и repeat-use scenarios.' },
            { label: 'Delivered', value: 'Структура платформы, prototype ключевых flows, UI-direction и materials for next stage.' },
            { label: 'Suitable for', value: 'Service marketplaces, booking platforms, customer portals и transaction-based products.' },
          ],
          ctaLabel: 'Получить предложение',
          ctaHref: '/ru/get-proposal',
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'concepts-why',
          eyebrow: 'Why concepts matter',
          title: 'Зачем смотреть концепты до старта проекта',
          description:
            'Они помогают увидеть подход Atelier Meridian к структуре, narrative и visual direction ещё до начала конкретной работы.',
          variant: 'pillars',
          columns: '3',
          items: [
            { title: 'Понять уровень детализации', description: 'Как мы разбираем структуру, роли, screens и flows.' },
            { title: 'Увидеть visual direction', description: 'Как выглядит premium UI-подача для разных типов digital products.' },
            { title: 'Оценить fit с вашим проектом', description: 'Какие сценарии и deliverables будут релевантны именно вам.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'concepts-video',
          eyebrow: 'Walkthrough',
          title: 'Как концепт превращается в build-ready материал',
          description: 'Короткий walkthrough о том, как мы собираем продуктовую структуру, prototype и следующий шаг после концепта.',
          videoUrl: VIDEO_URL,
          note: 'Замените ссылку на финальный walkthrough в Strapi.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '/ru/get-proposal',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
        },
        {
          __component: 'page.cta',
          sectionId: 'concepts-cta',
          title: 'Нужен концепт под ваш проект?',
          description: 'Расскажите о продукте, и мы предложим формат работы, сроки и стартовую стоимость.',
          buttonLabel: 'Получить предложение',
          buttonHref: '/ru/get-proposal',
        },
      ],
    },
    {
      title: 'Получить предложение',
      slug: 'get-proposal',
      template: 'get-proposal',
      seo: {
        metaTitle: 'Получить предложение | Atelier Meridian',
        metaDescription:
          'Опишите сайт, портал, B2B-систему, dashboard или mobile app. Мы предложим формат работы, сроки и стартовую стоимость.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'proposal-hero',
          eyebrow: 'Project intake',
          title: 'Закажите дизайн сайта, системы или мобильного приложения',
          description:
            'Расскажите, что вы планируете — сайт, корпоративный портал, B2B-систему, dashboard или mobile app. Мы предложим формат работы, сроки и стоимость без обязательного стартового звонка.',
          primaryCtaLabel: 'Заполнить brief',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
          tags: [
            { label: 'No-call-first' },
            { label: '24–48h reply' },
            { label: 'Files accepted' },
            { label: 'Arabic / RTL friendly' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-paths',
          eyebrow: 'Choose a path',
          title: 'Выберите удобный способ начать',
          description: 'Можно кратко заполнить форму или сразу прислать материалы проекта. В обоих случаях мы подготовим следующий шаг.',
          variant: 'conversion-paths',
          columns: '2',
          items: [
            {
              title: 'Заполнить brief проекта',
              description: 'Подходит, если хотите получить рекомендацию по формату работы, ориентир по срокам и стартовую стоимость.',
              buttonLabel: 'Перейти к brief',
              buttonHref: '#proposal-form',
            },
            {
              title: 'Загрузить материалы проекта',
              description: 'Подходит, если у вас уже есть notes, PRD, старые screens, документы, ссылки или draft-описание.',
              buttonLabel: 'Прикрепить материалы',
              buttonHref: '#proposal-form',
            },
          ],
        },
        {
          __component: 'page.steps',
          sectionId: 'proposal-process',
          eyebrow: 'How we review intake',
          title: 'Как мы обрабатываем intake проекта',
          description: 'Нам нужно понять цель, роли, ограничения и следующий шаг — без лишних созвонов и затянутого пресейла.',
          variant: 'proposal',
          items: [
            { number: '01', title: 'Цели проекта', description: 'Фиксируем, зачем нужен проект и какой результат для вас важен.' },
            { number: '02', title: 'Роли и сценарии', description: 'Определяем, кто будет работать с продуктом и какие сценарии критичны.' },
            { number: '03', title: 'Ограничения и scope', description: 'Учитываем сроки, сложность, доступные материалы и объем проработки.' },
            { number: '04', title: 'Следующий шаг', description: 'Предлагаем формат работы, ориентир по срокам и стартовую стоимость.' },
          ],
        },
        {
          __component: 'page.form-section',
          sectionId: 'proposal-form',
          title: 'Краткий brief проекта',
          description:
            'Опишите проект, цель, сроки и приложите материалы. Этого достаточно, чтобы мы подготовили структурированное предложение.',
          submitLabel: 'Отправить brief',
          successMessage: 'После отправки мы вернемся к вам с рекомендацией по формату работы, срокам и стартовой стоимости.',
          acceptsFiles: true,
          maxFileSizeMb: 50,
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-trust',
          eyebrow: 'Why this intake works',
          title: 'Структурный intake для сложных digital-проектов',
          description: 'Формат, который подходит для product-led, B2B и enterprise задач.',
          variant: 'trust',
          columns: '4',
          items: [
            { title: 'Подходит для сложных workflow', description: 'Структурируем многоуровневые процессы, role-based системы и enterprise-задачи.' },
            { title: 'Удобно для startup, B2B и enterprise', description: 'Работаем с founders, product teams, агентствами и integrators.' },
            { title: 'Поддерживает white-label модель', description: 'Готовим материалы под бренд клиента для агентств и партнёров.' },
            { title: 'Упрощает передачу в разработку', description: 'Формируем build-ready материалы и документацию для delivery-команды.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'proposal-video',
          eyebrow: 'Walkthrough',
          title: 'Как выглядит путь после brief',
          description: 'Показываем, как intake превращается в product framing, prototype и build-ready handoff materials.',
          videoUrl: VIDEO_URL,
          note: 'Позже можно заменить на финальный walkthrough.',
          primaryCtaLabel: 'Получить предложение',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'Посмотреть цены',
          secondaryCtaHref: '/ru/pricing',
        },
        {
          __component: 'page.faq',
          sectionId: 'proposal-faq',
          title: 'Частые вопросы',
          items: [
            { question: 'Что я получу после отправки brief?', answer: 'Вы получите структурированное предложение с рекомендацией по формату работы, ориентиром по срокам и стартовой стоимостью.' },
            { question: 'Можно ли работать без звонков?', answer: 'Да. Мы поддерживаем no-call-first формат. Большинство вопросов решается через brief, email и asynchronous communication.' },
            { question: 'Можно ли прийти с rough notes или старой системой?', answer: 'Да. Вы можете загрузить заметки, screenshots, старые экраны, PRD или просто описание проекта.' },
            { question: 'Поддерживаете ли вы white-label формат?', answer: 'Да. Мы работаем с агентствами, integrators и консультантами, которым нужны материалы под бренд клиента.' },
            { question: 'Работаете ли вы с multilingual и Arabic / RTL?', answer: 'Да. Мы учитываем multilingual-продукты, включая Arabic и RTL-интерфейсы.' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-support',
          eyebrow: 'Alternative path',
          title: 'Не хотите заполнять всё вручную?',
          description: 'Пришлите материалы проекта — мы все равно сможем подготовить структурированное предложение.',
          variant: 'decision-support',
          columns: '2',
          items: [
            { title: 'Загрузить материалы', description: 'PRD, brief, screenshots, старые экраны, Figma, links или draft-описание проекта.', buttonLabel: 'Прикрепить материалы', buttonHref: '#proposal-form' },
            { title: 'Посмотреть форматы работы', description: 'Если хотите сначала понять варианты сотрудничества, перейдите на страницу pricing.', buttonLabel: 'Посмотреть цены', buttonHref: '/ru/pricing' },
          ],
        },
        {
          __component: 'page.cta',
          sectionId: 'proposal-final-cta',
          title: 'Готовы описать проект?',
          description: 'Даже rough brief достаточно, чтобы мы предложили следующий шаг и стартовую стоимость.',
          buttonLabel: 'Перейти к brief',
          buttonHref: '#proposal-form',
        },
      ],
    },
  ],
  en: [
    {
      title: 'Concepts',
      slug: 'concepts',
      template: 'concepts',
      seo: {
        metaTitle: 'Studio Concepts | Atelier Meridian',
        metaDescription:
          'Demonstration projects showing how Atelier Meridian approaches websites, digital systems, client portals, dashboards, and mobile apps.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'concepts-hero',
          eyebrow: 'Studio Concepts',
          title: 'Concepts that show how your product can look before development begins',
          description:
            'A curated set of demonstration directions by Atelier Meridian — websites, digital systems, client portals, SaaS interfaces, and mobile apps.',
          primaryCtaLabel: 'Get proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'See pricing',
          secondaryCtaHref: '/en/pricing',
          tags: [
            { label: 'B2B systems' },
            { label: 'Mobile apps' },
            { label: 'Client portals' },
            { label: 'Corporate websites' },
          ],
        },
        {
          __component: 'page.rich-text',
          sectionId: 'concepts-intro',
          title: 'Not templates — references for product clarity and presentation',
          body:
            'These concepts show how Atelier Meridian structures a complex digital product before development: from narrative and screen architecture to prototype and handoff materials.',
        },
        {
          __component: 'page.concept-nav',
          sectionId: 'concepts-nav',
          title: 'Typical concept directions',
          items: EN_CONCEPT_ITEMS.map((item) => ({ anchorId: item.id, label: item.label })),
        },
        {
          __component: 'page.concept-section',
          sectionId: 'b2b-platform',
          categoryLabel: 'B2B SYSTEM DESIGN',
          title: 'B2B Platform & Internal System',
          intro:
            'A concept built for a complex operational environment where workflows, roles, approvals, and team logic need to come together inside one clear digital system.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Turn a complex operational workflow into one coherent system with multiple user roles, approval paths, and dashboard logic.' },
            { label: 'Structured', value: 'Roles and permissions, key user flows, the product screen map, module logic, and day-to-day team scenarios.' },
            { label: 'Delivered', value: 'A premium prototype, interface system direction, the structure of the key screens, and materials for development.' },
            { label: 'Suitable for', value: 'B2B platforms, internal systems, operational tools, and complex admin interfaces.' },
          ],
          ctaLabel: 'Discuss a similar project',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'mobile-app',
          categoryLabel: 'MOBILE APP DESIGN',
          title: 'Mobile App Design',
          intro: 'A mobile-first concept shaped so it can be shown to investors, used in a pitch, or taken forward as a credible base for the next development stage.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Package a fintech or service product into a clear mobile-first format for investors and the delivery team.' },
            { label: 'Structured', value: 'User flows, onboarding logic, priority modules, financial screens, and the overall app structure.' },
            { label: 'Delivered', value: 'An investor-ready prototype, visual direction, key screens, and materials for the next development stage.' },
            { label: 'Suitable for', value: 'Mobile apps, MVPs, investor-ready concepts, and redesign of existing mobile products.' },
          ],
          ctaLabel: 'Get proposal',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'client-portal',
          categoryLabel: 'PORTAL & DASHBOARD DESIGN',
          title: 'Client Portal & Dashboard',
          intro: 'A service concept where a complex process is turned into a clear client portal with transparent navigation, status logic, workflow structure, and role-based access.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Turn a complex service process into a clear client portal with transparent navigation, workflow logic, and role-based structure.' },
            { label: 'Structured', value: 'Portal architecture, user scenarios, service statuses, the screen matrix, and the key interaction points.' },
            { label: 'Delivered', value: 'The interface structure, a prototype of the key screens, UI direction, and a package of materials for development.' },
            { label: 'Suitable for', value: 'Service portals, account areas, dashboards, and internal service interfaces.' },
          ],
          ctaLabel: 'Discuss a portal',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'b2b-website',
          categoryLabel: 'WEBSITE DESIGN',
          title: 'Corporate Website for a B2B Company',
          intro: 'A corporate website concept designed to help a premium B2B company explain a complex service more clearly, build trust faster, and create a stronger first impression.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Create a premium corporate website that explains a complex service clearly and strengthens trust at the first point of contact.' },
            { label: 'Structured', value: 'Site architecture, content hierarchy, key page logic, navigation paths, and the way a complex B2B offer is presented.' },
            { label: 'Delivered', value: 'A visual website concept, the structure of the main pages, a UI system for the web interface, and materials for development.' },
            { label: 'Suitable for', value: 'B2B companies, integrators, outsourcing teams, technology services, and premium corporate websites.' },
          ],
          ctaLabel: 'I need a similar website',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'startup-landing',
          categoryLabel: 'STARTUP WEBSITE DESIGN',
          title: 'Investor-Ready Landing Page for a Startup Product',
          intro: 'A landing page concept for an early-stage product, built to make the idea easier to explain to investors, partners, and early users.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Package an early-stage product into a landing page that quickly explains the idea, value, and core user logic.' },
            { label: 'Structured', value: 'The first-screen logic, product narrative, order of the content blocks, key proof points, and visual direction.' },
            { label: 'Delivered', value: 'A landing page concept, site structure, visual direction, and a set of key screens for launch or presentation.' },
            { label: 'Suitable for', value: 'Startup websites, launch pages, investor presentations, and early-stage positioning.' },
          ],
          ctaLabel: 'Get proposal',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'saas-interface',
          categoryLabel: 'WEB PRODUCT DESIGN',
          title: 'SaaS Interface for a Web Product',
          intro: 'A web product concept where complex functionality is shaped into a clear, scalable, and product-mature interface system.',
          layout: 'imageRight',
          details: [
            { label: 'Challenge', value: 'Design a web product interface so that complex functionality feels clear, modern, and ready to scale.' },
            { label: 'Structured', value: 'Key user flows, screen architecture, product modules, priority workflows, and hierarchy of sections.' },
            { label: 'Delivered', value: 'A web product prototype, the structure of key screens, a basic component system, and materials for development.' },
            { label: 'Suitable for', value: 'SaaS products, dashboards, web products, startup software, and B2B digital tools.' },
          ],
          ctaLabel: 'Discuss SaaS UX/UI',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'booking-platform',
          categoryLabel: 'SERVICE PLATFORM DESIGN',
          title: 'Service Platform / Booking Interface',
          intro: 'A customer-facing platform concept where a complex service is turned into clear search, selection, booking flow, and a more transparent user journey.',
          layout: 'imageLeft',
          details: [
            { label: 'Challenge', value: 'Turn a complex customer service into a clear digital product with transparent search, selection, and booking flow.' },
            { label: 'Structured', value: 'The customer journey from choice to booking, service logic, decision points, statuses, and repeat-use scenarios.' },
            { label: 'Delivered', value: 'The platform structure, a prototype of the key flows, UI direction, and materials for the next product stage.' },
            { label: 'Suitable for', value: 'Service marketplaces, booking platforms, customer portals, and products with transaction flows.' },
          ],
          ctaLabel: 'Get proposal',
          ctaHref: '/en/get-proposal',
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'concepts-why',
          eyebrow: 'Why concepts matter',
          title: 'Why browse concepts before the project starts',
          description: 'They show how Atelier Meridian thinks about product structure, narrative, and visual direction before any delivery starts.',
          variant: 'pillars',
          columns: '3',
          items: [
            { title: 'See the level of thinking', description: 'How we approach roles, screens, structure, and workflows.' },
            { title: 'Understand the visual direction', description: 'What premium UI can look like for different product types.' },
            { title: 'Check fit with your project', description: 'Which scenarios and deliverables are most relevant to your case.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'concepts-video',
          eyebrow: 'Walkthrough',
          title: 'How a concept becomes build-ready material',
          description: 'A short walkthrough of how we move from concept and product framing to prototype and handoff materials.',
          videoUrl: VIDEO_URL,
          note: 'Replace with the final walkthrough URL in Strapi.',
          primaryCtaLabel: 'Get proposal',
          primaryCtaHref: '/en/get-proposal',
          secondaryCtaLabel: 'See pricing',
          secondaryCtaHref: '/en/pricing',
        },
        {
          __component: 'page.cta',
          sectionId: 'concepts-cta',
          title: 'Need a concept for your product?',
          description: 'Tell us about the project, and we will recommend a suitable format, timeline, and starting price.',
          buttonLabel: 'Get proposal',
          buttonHref: '/en/get-proposal',
        },
      ],
    },
    {
      title: 'Get proposal',
      slug: 'get-proposal',
      template: 'get-proposal',
      seo: {
        metaTitle: 'Get proposal | Atelier Meridian',
        metaDescription:
          'Tell us about your website, portal, B2B system, dashboard, or mobile app. We will recommend a working format, timeline, and starting price.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'proposal-hero',
          eyebrow: 'Project intake',
          title: 'Request a proposal for your website, system, or mobile app',
          description:
            'Tell us what you are planning — a website, client portal, B2B system, dashboard, or mobile app. We will recommend a suitable format, timeline, and price without a mandatory kickoff call.',
          primaryCtaLabel: 'Fill in the brief',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'See pricing',
          secondaryCtaHref: '/en/pricing',
          tags: [
            { label: 'No-call-first' },
            { label: '24–48h reply' },
            { label: 'Files accepted' },
            { label: 'Arabic / RTL friendly' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-paths',
          eyebrow: 'Choose a path',
          title: 'Choose the easiest way to start',
          description: 'You can fill in a short brief or send project materials right away. In both cases we prepare the next recommended step.',
          variant: 'conversion-paths',
          columns: '2',
          items: [
            {
              title: 'Fill in the project brief',
              description: 'Best if you want a recommended working format, timeline estimate, and a starting price.',
              buttonLabel: 'Open brief',
              buttonHref: '#proposal-form',
            },
            {
              title: 'Upload project materials',
              description: 'Best if you already have notes, PRD, screenshots, docs, links, or a rough project description.',
              buttonLabel: 'Attach materials',
              buttonHref: '#proposal-form',
            },
          ],
        },
        {
          __component: 'page.steps',
          sectionId: 'proposal-process',
          eyebrow: 'How we review intake',
          title: 'How we process project intake',
          description: 'We need to understand the goal, the roles, the constraints, and the next step — without unnecessary calls or bloated presale cycles.',
          variant: 'proposal',
          items: [
            { number: '01', title: 'Project goal', description: 'We clarify why the project matters and which result is important for you.' },
            { number: '02', title: 'Roles and scenarios', description: 'We define who will use the product and which user scenarios are critical.' },
            { number: '03', title: 'Constraints and scope', description: 'We consider timing, complexity, available materials, and the required level of detail.' },
            { number: '04', title: 'Recommended next step', description: 'We suggest a suitable format, timeline estimate, and starting price.' },
          ],
        },
        {
          __component: 'page.form-section',
          sectionId: 'proposal-form',
          title: 'Project brief',
          description: 'Describe the project, the goal, the timeline, and attach any relevant materials. This is enough for us to prepare a structured proposal.',
          submitLabel: 'Send brief',
          successMessage: 'After submission we will come back with a recommended working format, timeline, and starting price.',
          acceptsFiles: true,
          maxFileSizeMb: 50,
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-trust',
          eyebrow: 'Why this intake works',
          title: 'Structured intake for complex digital projects',
          description: 'A format that works well for startup, B2B, and enterprise product situations.',
          variant: 'trust',
          columns: '4',
          items: [
            { title: 'Fits complex workflows', description: 'We structure multi-step processes, role-based systems, and enterprise use cases.' },
            { title: 'Works for startup, B2B, and enterprise', description: 'We collaborate with founders, product teams, agencies, and integrators.' },
            { title: 'Supports white-label delivery', description: 'We can prepare materials under your client or partner brand.' },
            { title: 'Makes handoff easier', description: 'We package build-ready materials and documentation for development teams.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'proposal-video',
          eyebrow: 'Walkthrough',
          title: 'What happens after the brief',
          description: 'We show how intake turns into product framing, prototype, and build-ready handoff materials.',
          videoUrl: VIDEO_URL,
          note: 'Replace later with the final walkthrough.',
          primaryCtaLabel: 'Get proposal',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'See pricing',
          secondaryCtaHref: '/en/pricing',
        },
        {
          __component: 'page.faq',
          sectionId: 'proposal-faq',
          title: 'Frequently asked questions',
          items: [
            { question: 'What do I get after sending the brief?', answer: 'You receive a structured proposal with a recommended working format, timeline estimate, and starting price.' },
            { question: 'Can we work without calls?', answer: 'Yes. We support a no-call-first process. Most questions are handled through the brief, email, and async communication.' },
            { question: 'Can I come with rough notes or a legacy system?', answer: 'Yes. You can upload notes, screenshots, PRD, old screens, or just describe the project in words.' },
            { question: 'Do you support white-label collaboration?', answer: 'Yes. We work with agencies, integrators, and consultants who need materials under their own client brand.' },
            { question: 'Do you work with multilingual and Arabic / RTL products?', answer: 'Yes. We account for multilingual products, including Arabic and RTL interfaces.' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-support',
          eyebrow: 'Alternative path',
          title: 'Do not want to fill everything manually?',
          description: 'Send whatever project materials you already have — we can still prepare a structured next step.',
          variant: 'decision-support',
          columns: '2',
          items: [
            { title: 'Upload materials', description: 'PRD, brief, screenshots, old screens, Figma files, links, or a rough project description.', buttonLabel: 'Attach materials', buttonHref: '#proposal-form' },
            { title: 'Review pricing first', description: 'If you want to understand the collaboration formats first, open the pricing page.', buttonLabel: 'See pricing', buttonHref: '/en/pricing' },
          ],
        },
        {
          __component: 'page.cta',
          sectionId: 'proposal-final-cta',
          title: 'Ready to describe the project?',
          description: 'Even a rough brief is enough for us to suggest the next step and a starting price.',
          buttonLabel: 'Go to brief',
          buttonHref: '#proposal-form',
        },
      ],
    },
  ],
  ar: [
    {
      title: 'المفاهيم',
      slug: 'concepts',
      template: 'concepts',
      seo: {
        metaTitle: 'مفاهيم الاستوديو | Atelier Meridian',
        metaDescription:
          'مشاريع توضيحية تُظهر كيف يتعامل Atelier Meridian مع المواقع والأنظمة الرقمية وبوابات العملاء ولوحات التحكم وتطبيقات الجوال.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'concepts-hero',
          eyebrow: 'Studio Concepts',
          title: 'مفاهيم تُظهر كيف يمكن أن يبدو منتجك قبل بدء التطوير',
          description:
            'مجموعة مختارة من الاتجاهات التوضيحية من Atelier Meridian — مواقع، أنظمة رقمية، بوابات عملاء، واجهات SaaS، وتطبيقات جوال.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'الأسعار',
          secondaryCtaHref: '/ar/pricing',
          tags: [
            { label: 'أنظمة B2B' },
            { label: 'تطبيقات جوال' },
            { label: 'بوابات عملاء' },
            { label: 'مواقع شركات' },
          ],
        },
        {
          __component: 'page.rich-text',
          sectionId: 'concepts-intro',
          title: 'ليست قوالب، بل مراجع لتوضيح المنتج وعرضه',
          body:
            'توضح هذه المفاهيم كيف يقوم Atelier Meridian بهيكلة منتج رقمي معقد قبل التطوير: من السرد والبنية الشاشية إلى النموذج التفاعلي ومواد التسليم.',
        },
        {
          __component: 'page.concept-nav',
          sectionId: 'concepts-nav',
          title: 'اتجاهات مفاهيم نموذجية',
          items: AR_CONCEPT_ITEMS.map((item) => ({ anchorId: item.id, label: item.label })),
        },
        {
          __component: 'page.concept-section',
          sectionId: 'b2b-platform',
          categoryLabel: 'تصميم أنظمة B2B',
          title: 'منصة B2B ونظام داخلي',
          intro: 'مفهوم لبيئة تشغيل معقدة حيث يجب جمع سير العمل والأدوار والموافقات ومنطق الفريق داخل نظام رقمي واضح واحد.',
          layout: 'imageLeft',
          details: [
            { label: 'التحدي', value: 'تحويل سير عمل تشغيلي معقد إلى نظام متماسك واحد مع أدوار متعددة ومسارات موافقة ومنطق لوحة تحكم.' },
            { label: 'ما الذي نهيكله', value: 'الأدوار والصلاحيات، مسارات المستخدم الرئيسية، خريطة الشاشات، منطق الوحدات، وسيناريوهات العمل اليومية.' },
            { label: 'ما الذي نُسلّمه', value: 'نموذج تفاعلي مميز، اتجاه بصري للواجهة، بنية الشاشات الأساسية، ومواد للتطوير.' },
            { label: 'مناسب لـ', value: 'منصات B2B، الأنظمة الداخلية، الأدوات التشغيلية، وواجهات الإدارة المعقدة.' },
          ],
          ctaLabel: 'ناقش مشروعاً مشابهاً',
          ctaHref: '/ar/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'mobile-app',
          categoryLabel: 'تصميم تطبيقات الجوال',
          title: 'تصميم تطبيق جوال',
          intro: 'مفهوم mobile-first يمكن عرضه على المستثمرين أو استخدامه في pitch أو الاعتماد عليه كأساس موثوق للمرحلة التالية من التطوير.',
          layout: 'imageRight',
          details: [
            { label: 'التحدي', value: 'تغليف منتج مالي أو خدمي في صيغة mobile-first واضحة للمستثمر وفريق التنفيذ.' },
            { label: 'ما الذي نهيكله', value: 'مسارات المستخدم، منطق onboarding، الوحدات ذات الأولوية، والشاشات الرئيسية.' },
            { label: 'ما الذي نُسلّمه', value: 'نموذج تفاعلي جاهز للمستثمر، اتجاه بصري، الشاشات الأساسية، ومواد للمرحلة التالية.' },
            { label: 'مناسب لـ', value: 'تطبيقات الجوال، MVP، مفاهيم جاهزة للمستثمر، وإعادة تصميم التطبيقات.' },
          ],
          ctaLabel: 'اطلب عرضاً',
          ctaHref: '/ar/get-proposal',
        },
        {
          __component: 'page.concept-section',
          sectionId: 'client-portal',
          categoryLabel: 'تصميم البوابات ولوحات التحكم',
          title: 'بوابة عميل ولوحة تحكم',
          intro: 'مفهوم خدمة يحول العملية المعقدة إلى بوابة عميل واضحة مع تنقل شفاف ومنطق حالات وسير عمل وبنية مبنية على الأدوار.',
          layout: 'imageLeft',
          details: [
            { label: 'التحدي', value: 'تحويل عملية خدمة معقدة إلى بوابة عميل واضحة مع تنقل ومنطق سير عمل وبنية قائمة على الأدوار.' },
            { label: 'ما الذي نهيكله', value: 'معمارية البوابة، سيناريوهات المستخدم، حالات الخدمة، مصفوفة الشاشات، ونقاط التفاعل الرئيسية.' },
            { label: 'ما الذي نُسلّمه', value: 'بنية الواجهة، نموذج للشاشات الأساسية، اتجاه UI، وحزمة مواد للتطوير.' },
            { label: 'مناسب لـ', value: 'بوابات الخدمات، مناطق الحسابات، لوحات التحكم، والواجهات الخدمية الداخلية.' },
          ],
          ctaLabel: 'ناقش بوابة مماثلة',
          ctaHref: '/ar/get-proposal',
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'concepts-why',
          eyebrow: 'Why concepts matter',
          title: 'لماذا من المفيد مراجعة المفاهيم قبل بدء المشروع',
          description: 'لأنها تُظهر طريقة Atelier Meridian في التفكير في البنية والسرد والاتجاه البصري قبل بدء التنفيذ.',
          variant: 'pillars',
          columns: '3',
          items: [
            { title: 'فهم مستوى العمل', description: 'كيف نتعامل مع الأدوار والشاشات والبنية وتدفقات المستخدم.' },
            { title: 'رؤية الاتجاه البصري', description: 'كيف يمكن أن يبدو UI المتميز لأنواع مختلفة من المنتجات.' },
            { title: 'تقييم ملاءمة المشروع', description: 'أي السيناريوهات والمخرجات هي الأكثر صلة بحالتك.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'concepts-video',
          eyebrow: 'Walkthrough',
          title: 'كيف يتحول المفهوم إلى مواد جاهزة للتنفيذ',
          description: 'عرض سريع لكيفية الانتقال من المفهوم وتأطير المنتج إلى النموذج التفاعلي ومواد التسليم.',
          videoUrl: VIDEO_URL,
          note: 'يمكن استبدال الرابط لاحقاً داخل Strapi.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '/ar/get-proposal',
          secondaryCtaLabel: 'الأسعار',
          secondaryCtaHref: '/ar/pricing',
        },
        {
          __component: 'page.cta',
          sectionId: 'concepts-cta',
          title: 'هل تحتاج إلى مفهوم خاص بمشروعك؟',
          description: 'أخبرنا عن المنتج، وسنقترح تنسيق العمل والمدة والسعر الابتدائي.',
          buttonLabel: 'اطلب عرضاً',
          buttonHref: '/ar/get-proposal',
        },
      ],
    },
    {
      title: 'اطلب عرضاً',
      slug: 'get-proposal',
      template: 'get-proposal',
      seo: {
        metaTitle: 'اطلب عرضاً | Atelier Meridian',
        metaDescription:
          'أخبرنا عن الموقع أو البوابة أو نظام B2B أو لوحة التحكم أو تطبيق الجوال. سنقترح تنسيق العمل والمدة والسعر الابتدائي.',
      },
      blocks: [
        {
          __component: 'page.hero',
          sectionId: 'proposal-hero',
          eyebrow: 'Project intake',
          title: 'اطلب عرضاً لتصميم موقع أو نظام أو تطبيق جوال',
          description:
            'أخبرنا بما تخطط له — موقع، بوابة عميل، نظام B2B، لوحة تحكم، أو تطبيق جوال. سنقترح تنسيق العمل والمدة والسعر من دون مكالمة إلزامية في البداية.',
          primaryCtaLabel: 'املأ الـ brief',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'الأسعار',
          secondaryCtaHref: '/ar/pricing',
          tags: [
            { label: 'بدون مكالمة أولية' },
            { label: 'رد خلال 24–48 ساعة' },
            { label: 'يمكن إرفاق ملفات' },
            { label: 'يدعم Arabic / RTL' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-paths',
          eyebrow: 'Choose a path',
          title: 'اختر الطريقة الأسهل للبدء',
          description: 'يمكنك تعبئة brief مختصر أو إرسال مواد المشروع مباشرة. في الحالتين سنقترح الخطوة التالية المناسبة.',
          variant: 'conversion-paths',
          columns: '2',
          items: [
            {
              title: 'املأ brief المشروع',
              description: 'مناسب إذا كنت تريد تنسيق العمل المقترح، وتقدير المدة، والسعر الابتدائي.',
              buttonLabel: 'فتح brief',
              buttonHref: '#proposal-form',
            },
            {
              title: 'أرفق مواد المشروع',
              description: 'مناسب إذا كانت لديك ملاحظات أو PRD أو screenshots أو روابط أو وصف أولي للمشروع.',
              buttonLabel: 'إرفاق المواد',
              buttonHref: '#proposal-form',
            },
          ],
        },
        {
          __component: 'page.steps',
          sectionId: 'proposal-process',
          eyebrow: 'How we review intake',
          title: 'كيف نراجع طلب المشروع',
          description: 'نحتاج إلى فهم الهدف والأدوار والقيود والخطوة التالية — من دون مكالمات زائدة أو presale مرهق.',
          variant: 'proposal',
          items: [
            { number: '01', title: 'هدف المشروع', description: 'نوضح لماذا يهم المشروع وما النتيجة المهمة لكم.' },
            { number: '02', title: 'الأدوار والسيناريوهات', description: 'نحدد من سيستخدم المنتج وأي سيناريوهات هي الأهم.' },
            { number: '03', title: 'القيود والنطاق', description: 'نأخذ في الاعتبار التوقيت والتعقيد والمواد المتاحة ومستوى التفصيل المطلوب.' },
            { number: '04', title: 'الخطوة التالية المقترحة', description: 'نقترح تنسيق عمل مناسباً مع تقدير للمدة والسعر الابتدائي.' },
          ],
        },
        {
          __component: 'page.form-section',
          sectionId: 'proposal-form',
          title: 'Brief المشروع',
          description: 'صف المشروع والهدف والمدة الزمنية وأرفق أي مواد ذات صلة. هذا يكفي لنعد عرضاً منظماً.',
          submitLabel: 'إرسال brief',
          successMessage: 'بعد الإرسال سنعود إليك باقتراح لتنسيق العمل والمدة والسعر الابتدائي.',
          acceptsFiles: true,
          maxFileSizeMb: 50,
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-trust',
          eyebrow: 'Why this intake works',
          title: 'استقبال منظم للمشاريع الرقمية المعقدة',
          description: 'تنسيق مناسب لسيناريوهات startup وB2B وenterprise.',
          variant: 'trust',
          columns: '4',
          items: [
            { title: 'مناسب لتدفقات العمل المعقدة', description: 'نهيكل العمليات متعددة الخطوات والأنظمة القائمة على الأدوار وحالات الاستخدام المؤسسية.' },
            { title: 'ملائم لـ startup وB2B وenterprise', description: 'نعمل مع founders وفرق المنتجات والوكالات وintegrators.' },
            { title: 'يدعم white-label', description: 'يمكننا إعداد المواد تحت علامة العميل أو الشريك.' },
            { title: 'يسهّل التسليم للتطوير', description: 'نرتب مواد جاهزة للبناء ووثائق واضحة لفريق التطوير.' },
          ],
        },
        {
          __component: 'page.video-section',
          sectionId: 'proposal-video',
          eyebrow: 'Walkthrough',
          title: 'ماذا يحدث بعد إرسال brief',
          description: 'نوضح كيف يتحول intake إلى product framing ونموذج تفاعلي ومواد جاهزة للتسليم.',
          videoUrl: VIDEO_URL,
          note: 'يمكن استبدال الرابط لاحقاً بالفيديو النهائي.',
          primaryCtaLabel: 'اطلب عرضاً',
          primaryCtaHref: '#proposal-form',
          secondaryCtaLabel: 'الأسعار',
          secondaryCtaHref: '/ar/pricing',
        },
        {
          __component: 'page.faq',
          sectionId: 'proposal-faq',
          title: 'الأسئلة الشائعة',
          items: [
            { question: 'ماذا سأحصل عليه بعد إرسال الـ brief؟', answer: 'ستحصل على عرض منظم يتضمن تنسيق العمل المقترح وتقدير المدة والسعر الابتدائي.' },
            { question: 'هل يمكن العمل من دون مكالمات؟', answer: 'نعم. نعتمد عملية no-call-first. تتم أغلب الأسئلة عبر الـ brief والبريد والتواصل غير المتزامن.' },
            { question: 'هل يمكنني البدء بملاحظات أولية أو نظام قديم؟', answer: 'نعم. يمكنك رفع الملاحظات أو screenshots أو PRD أو الشاشات القديمة أو وصف المشروع بالكلمات.' },
            { question: 'هل تدعمون التعاون بصيغة white-label؟', answer: 'نعم. نعمل مع الوكالات وintegrators والاستشاريين الذين يحتاجون مواداً تحت علامة عميلهم.' },
            { question: 'هل تعملون مع المنتجات متعددة اللغات وArabic / RTL؟', answer: 'نعم. نأخذ في الاعتبار المنتجات متعددة اللغات، بما فيها العربية وواجهات RTL.' },
          ],
        },
        {
          __component: 'page.cards-grid',
          sectionId: 'proposal-support',
          eyebrow: 'Alternative path',
          title: 'لا تريد تعبئة كل شيء يدوياً؟',
          description: 'أرسل ما لديك من مواد المشروع، وسنتمكن مع ذلك من إعداد الخطوة التالية بشكل منظم.',
          variant: 'decision-support',
          columns: '2',
          items: [
            { title: 'إرفاق المواد', description: 'PRD أو brief أو screenshots أو شاشات قديمة أو ملفات Figma أو روابط أو وصف أولي للمشروع.', buttonLabel: 'إرفاق المواد', buttonHref: '#proposal-form' },
            { title: 'مراجعة الأسعار أولاً', description: 'إذا أردت فهم تنسيقات التعاون أولاً، افتح صفحة الأسعار.', buttonLabel: 'الأسعار', buttonHref: '/ar/pricing' },
          ],
        },
        {
          __component: 'page.cta',
          sectionId: 'proposal-final-cta',
          title: 'هل أنت مستعد لوصف المشروع؟',
          description: 'حتى brief أولي يكفي لنقترح الخطوة التالية والسعر الابتدائي.',
          buttonLabel: 'الانتقال إلى brief',
          buttonHref: '#proposal-form',
        },
      ],
    },
  ],
}
